/*
 * bitmap.c
 *
 *  Created on: 3 mei 2018
 *      Author: Samuel Benhaiem
 */

#include "bitmap.h"



//Bitmap function, please provide X, Y and choose between these bitmaps:
//	- yoshi happy "happy"
//	- boo sad "sad"
//	- arrow up "up"
//	- arrow down "down"
//	- arrow right "right"
//	- arrow left "left"



void draw_bitmap (int bitmap_selector, int x, int y, int backcolor) {

//______________________________________BITMAP ARRAYS___________________________________________________
/*

	int yoshi_happy [40][40] = {
			backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0x04,0x14,0x34,0x28,0x28,0x34,0x34,0x04,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0x08,0x14,0x14,0xff,0xff,0xff,0xff,0xff,0x34,0x08,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0x08,0x55,0xff,0xff,0x49,0x6d,0xff,backcolor,0xdb,0x6d,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xa4,0xe4,0xe4,0xe4,0x20,0x92,0xff,0xff,0xff,0x49,0x6d,0xff,backcolor,0xdb,0x6d,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0x80,0xe4,0xc4,backcolor,backcolor,0x92,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0x6d,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0x14,0x14,0x14,0x14,0xff,0xff,0xff,0x9a,0x34,0xff,0x24,0x08,0x14,0x14,0x14,0x04,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xc4,0x40,0x04,0x10,0x14,0x14,0x14,0x14,0x14,0x14,0x14,0x14,0x14,0x14,0x10,0x14,0x14,0x14,0x14,0x10,0x08,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0x20,0xc4,0xe4,0x40,0x04,0x14,0x14,0x14,0x79,0xff,0xff,0xff,0x55,0x14,0x14,0x14,0x14,0x14,0x10,0x04,0x14,0x08,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0x20,0xe4,0xe4,0x40,0x04,0x14,0x14,0xbe,0xff,0xff,0xff,0xff,0x59,0x14,0x14,0x14,0x14,0x14,0x10,0x0c,0x14,0x10,0x0c,0x0c,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0x20,0x20,backcolor,0x04,0x14,0x14,0xdf,0xff,0xff,0xff,0xff,0x59,0x14,0x14,0x14,0x14,0x14,0x14,0x14,0x14,0x14,0x14,0x10,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0x04,0x14,0x14,0xdf,0xff,0xff,0xff,0xff,0x4d,0x0c,0x14,0x14,0x14,0x14,0x14,0x14,0x14,0x14,0x14,0x10,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0x60,0x64,0x04,0x14,0x34,0xbe,0xff,0xff,0x49,backcolor,0x08,0x14,0x14,0x14,0x14,0x14,0x14,0x14,0x14,0x14,0x10,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0x20,0x20,backcolor,0x04,0x10,0x9a,0xff,0xff,0xb6,0x24,0x08,0x14,0x14,0x14,0x14,0x14,0x14,0x14,0x14,0x10,0x08,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0x20,0x80,backcolor,0x10,0x34,0x9a,0xff,0xff,0xb6,0x4d,0x08,0x14,0x14,0x14,0x14,0x14,0x08,0x08,0x04,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0x20,0x40,backcolor,0x10,0x14,0x34,0xff,0xff,0xb6,0x49,backcolor,0x08,0x08,0x08,0x08,0x08,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0x80,0x92,0x24,backcolor,backcolor,backcolor,0x10,0x14,0x34,0xff,0xff,0x49,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0x20,0x80,0xe4,0x8d,0x24,backcolor,0x08,0x08,0x10,0x55,0x9a,0xff,0xff,0x49,0x24,0x6d,0x08,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0x49,0x68,0x80,0x80,0x08,0x08,0x0c,0x14,0x14,0x0c,0x96,0xff,0xff,0xff,0x49,0x24,0x92,0x75,0x0c,0x04,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0x08,0x08,0x71,0x49,backcolor,0x08,0x14,0x14,0x14,0x10,0x0c,0x4d,0xb6,0xff,0xff,0xff,0x49,backcolor,backcolor,0x92,0x14,0x08,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,0x28,0x59,0x14,0x04,0x04,0x08,0x14,0x14,0x14,0x14,0x10,0x04,0x92,0xdb,0xff,0xff,0xff,0x49,backcolor,backcolor,0x04,0x10,0x08,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,0x6d,0xff,0x59,0x04,0x08,0x14,0x14,0x14,0x14,0x14,0x14,0x0c,backcolor,0x92,0xff,0xff,0xff,0x49,backcolor,0x08,0x14,0x14,0x08,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,0x24,0xb6,0xff,0x24,0x08,0x14,0x14,0x14,0x14,0x14,0x10,0x04,backcolor,0x92,0xff,0xff,0xff,0x49,0x08,0x14,0x14,0x14,0x08,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xff,0x6d,0x08,0x10,0x14,0x14,0x14,0x14,0x14,0x0c,0x28,0xb6,0xff,0xff,0xff,0x49,0x04,0x0c,0x0c,0x0c,0x04,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xdb,0xdb,0x6d,backcolor,0x10,0x10,0x10,0x10,0x0c,0x24,0xdb,0xff,0xff,0xdb,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0x20,0x20,0x20,0x20,backcolor,backcolor,0x24,0xff,0xdb,0xdb,0xb6,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xc4,0xe4,0xe4,0xe4,0xe4,0x20,0x6d,0xff,0xff,0x20,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xc4,0xe4,0xe4,0xe4,0xe8,0x20,backcolor,backcolor,backcolor,0xe4,0x40,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xe4,0xe4,0xe4,0xe4,0xe8,0xff,0xe8,0x60,0x20,0xe4,0xe4,0xe4,0xec,0xff,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xe4,0xe4,0xe4,0xe4,0xe4,0xe4,0xe4,0x60,0x20,0xe4,0xe4,0xe4,0xe4,0xe4,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			};

	int boo_sad [40][40] = {
			0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff
			,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff
			,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff
			,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff
			,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff
			,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0x92,0x92,0x92,0x92,0x92,0x92,0x92,0x92,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff
			,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xdb,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0xdb,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff
			,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0x92,0x8d,0x8d,0x92,0x92,0x92,0x92,0x92,0x92,0x92,0x92,0x92,0x92,0x8d,0x8d,0x92,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff
			,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0x20,0x00,0x00,0x44,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0x44,0x00,0x00,0x20,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff
			,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0x8d,0x69,0xb6,0xb6,0xb6,0xb6,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xb6,0xb6,0xb6,0xb6,0x69,0x8d,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff
			,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0x44,0x00,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0x00,0x44,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff
			,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0x8d,0x44,0xb6,0xdb,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xdb,0xb6,0x44,0x8d,0xff,0xff,0xff,0xff,0xff,0xff,0xff
			,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0x69,0x00,0xdb,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xdb,0x00,0x69,0xff,0xff,0xff,0xff,0xff,0xff,0xff
			,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0x92,0x20,0xb6,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0x6d,0x20,0xdb,0xff,0x24,0x24,0xff,0xdb,0x00,0x69,0xff,0xff,0xff,0xff,0xff,0xff,0xff
			,0xff,0xff,0xff,0xff,0xff,0xff,0xb6,0x6d,0x20,0xb6,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0x69,0x00,0xdb,0xff,0x20,0x20,0xff,0xdb,0x20,0x6d,0xff,0xff,0xff,0xff,0xff,0xff,0xff
			,0xff,0xff,0xff,0xff,0xff,0x92,0x00,0x92,0xff,0xff,0xff,0x44,0x00,0x24,0x24,0x24,0x49,0xff,0xff,0xff,0xff,0xff,0xff,0x69,0x00,0xdb,0xff,0x20,0x20,0xff,0xff,0xff,0xb6,0x00,0x8d,0xff,0xff,0xff,0xff,0xff
			,0xff,0xff,0xff,0xff,0xff,0x92,0x00,0x92,0xff,0xff,0xff,0x44,0x00,0xdb,0xdb,0xdb,0xb6,0x49,0xff,0xff,0xff,0xff,0xff,0x69,0x00,0xdb,0xff,0x20,0x20,0xff,0xff,0xff,0xb6,0x00,0x8d,0xff,0xff,0xff,0xff,0xff
			,0xff,0xff,0xff,0xff,0xff,0xb6,0x49,0x92,0xb6,0xff,0xff,0x44,0x00,0xff,0xff,0xff,0xdb,0x6d,0xff,0xff,0xff,0xff,0xff,0x92,0x49,0xdb,0xff,0x49,0x49,0xff,0xff,0xff,0xb6,0x00,0x8d,0xff,0xff,0xff,0xff,0xff
			,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0x8d,0x00,0xb6,0xff,0x44,0x00,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xb6,0x00,0x8d,0xff,0xff,0xff,0xff,0xff
			,0xff,0xff,0xff,0xff,0xff,0xdb,0x92,0x92,0x6d,0xdb,0xff,0x92,0x6d,0x92,0xb6,0xff,0xff,0xff,0xff,0xff,0xff,0xfb,0xf6,0xfb,0xff,0xf6,0xf6,0xff,0xff,0xf6,0xf6,0xff,0xb6,0x00,0x8d,0xff,0xff,0xff,0xff,0xff
			,0xff,0xff,0xff,0xff,0xff,0x92,0x00,0x92,0xff,0xff,0xff,0xff,0xff,0x20,0x20,0xff,0xff,0xff,0xff,0xff,0xff,0xf2,0xe0,0xf6,0xff,0xe9,0xe0,0xff,0xff,0xe0,0xe9,0xff,0xb6,0x00,0x8d,0xff,0xff,0xff,0xff,0xff
			,0xff,0xff,0xff,0xff,0xff,0x92,0x00,0x92,0xff,0xff,0xff,0xff,0xff,0x92,0x92,0xff,0xff,0xff,0xff,0xff,0xff,0xf2,0xe0,0xed,0xf2,0xe4,0xe0,0xee,0xee,0xe0,0xe9,0xff,0xb6,0x00,0x8d,0xff,0xff,0xff,0xff,0xff
			,0xff,0xff,0xff,0xff,0xff,0x92,0x00,0x92,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xf2,0xe0,0xe0,0xe0,0xe0,0xe0,0xe0,0xe0,0xe0,0xe9,0xff,0xb6,0x00,0x8d,0xff,0xff,0xff,0xff,0xff
			,0xff,0xff,0xff,0xff,0xff,0x92,0x00,0x92,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xf2,0xe0,0xe0,0xe0,0xe0,0xe0,0xe0,0xe0,0xe0,0xe9,0xff,0xb6,0x00,0x8d,0xff,0xff,0xff,0xff,0xff
			,0xff,0xff,0xff,0xff,0xff,0x92,0x00,0x92,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xf2,0xe0,0xe0,0xe0,0xe0,0xe0,0xe0,0xe0,0xe0,0xe9,0xff,0xb6,0x00,0x8d,0xff,0xff,0xff,0xff,0xff
			,0xff,0xff,0xff,0xff,0xff,0x92,0x00,0x92,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xf6,0xe9,0xe4,0xe0,0xe0,0xe0,0xe0,0xe0,0xe0,0xe4,0xfb,0xd6,0x44,0x6d,0xdb,0xff,0xff,0xff,0xff,0xff,0xff
			,0xff,0xff,0xff,0xff,0xff,0x92,0x00,0x92,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xf6,0xe0,0xe0,0xe0,0xe0,0xe0,0xe0,0xe0,0xe0,0xe4,0xff,0xdb,0x00,0x69,0xff,0xff,0xff,0xff,0xff,0xff,0xff
			,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0x8d,0x20,0xb6,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xf6,0xe0,0xf2,0xff,0xed,0xe0,0xfb,0xff,0xe4,0xe4,0xff,0xdb,0x00,0x69,0xff,0xff,0xff,0xff,0xff,0xff,0xff
			,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0x92,0x20,0xb6,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xf6,0xe4,0xf2,0xff,0xed,0xe4,0xfb,0xff,0xe4,0xe4,0xff,0xdb,0x20,0x6d,0xff,0xff,0xff,0xff,0xff,0xff,0xff
			,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0x69,0x00,0xdb,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0x00,0x44,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff
			,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0x8d,0x44,0xb6,0xdb,0xdb,0xdb,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xdb,0xdb,0xdb,0xdb,0x44,0x6d,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff
			,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0x44,0x00,0x00,0x49,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0x44,0x00,0x00,0x20,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff
			,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0x8d,0x69,0x69,0x6d,0xb6,0xb6,0xb6,0xb6,0xb6,0xb6,0xb6,0xb6,0xb6,0xb6,0x6d,0x69,0x69,0x6d,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff
			,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0x92,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0xdb,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff
			,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xb6,0x8d,0x8d,0x8d,0x8d,0x8d,0x8d,0x8d,0x8d,0x8d,0x8d,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff
			,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff
			,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff
			,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff
			,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff
			,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff

			};

	int arrow_down [40][40] = {
			backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xdb,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xdb,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xdb,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xdb,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xdb,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xb6,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xdb,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xb6,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xb6,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xb6,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xb6,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xb6,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xb6,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xb6,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xb6,0xE0,0xE0,0xE0,0xE0,0xb6,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xE0,0xE0,0xE0,0xE0,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xb6,0xE0,0xE0,0xb6,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xE0,0xE0,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xb6,0xb6,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor


			};
	int arrow_up [40][40] = {
			backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xb6,0xb6,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xE0,0xE0,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xb6,0xE0,0xE0,0xb6,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xE0,0xE0,0xE0,0xE0,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xb6,0xE0,0xE0,0xE0,0xE0,0xb6,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xb6,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xb6,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xb6,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xb6,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xb6,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xb6,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xb6,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xdb,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xb6,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xdb,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xdb,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xdb,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xdb,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xdb,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor


			};

	int arrow_right [40][40] = {
			 backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xE0,0xdb,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xE0,0xE0,0xE0,0xdb,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xE0,0xE0,0xE0,0xE0,0xE0,0xb6,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xb6,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xb6,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xb6,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xb6,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xb6,backcolor,backcolor,backcolor,backcolor
			,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xb6,backcolor,backcolor
			,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xb6
			,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xb6
			,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xb6,backcolor,backcolor
			,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xb6,backcolor,backcolor,backcolor,backcolor
			,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xb6,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xb6,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xb6,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xdb,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xE0,0xE0,0xE0,0xE0,0xE0,0xdb,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xE0,0xE0,0xE0,0xdb,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xE0,0xdb,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor

			};

	int arrow_left [40][40] = {
			backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xdb,0xE0,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xb6,0xE0,0xE0,0xE0,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xdb,0xE0,0xE0,0xE0,0xE0,0xE0,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xdb,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xb6,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xb6,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xb6,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0
			,backcolor,backcolor,backcolor,backcolor,0xb6,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0
			,backcolor,backcolor,0xb6,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0
			,0xb6,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0
			,0xb6,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0
			,backcolor,backcolor,0xb6,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0
			,backcolor,backcolor,backcolor,backcolor,0xb6,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xb6,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xb6,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xb6,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xb6,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,0xE0,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xb6,0xE0,0xE0,0xE0,0xE0,0xE0,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xdb,0xE0,0xE0,0xE0,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,0xdb,0xE0,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor
			,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor,backcolor

			};


//______________________________________SETPIXEL FUNCTIONS___________________________________________________

	if (bitmap_selector == 0)	//YOSHI HAPPY setpixel funtion
	{
		for (int i=0; i<40; i++)
		{
			for (int j=0; j<40; j++)
			{
				int x_pos = j + x;
				int y_pos = i + y;
				UB_VGA_SetPixel(x_pos, y_pos, yoshi_happy[i][j]);
			}
		}
	}

	else if (bitmap_selector==1)	//BOO SAD setpixel function
	{
		for (int i=0; i<40; i++)
		{
			for (int j=0; j<40; j++)
			{
				int x_pos = j + x;
				int y_pos = i + y;
				UB_VGA_SetPixel(x_pos, y_pos, boo_sad[i][j]);
			}
		}
	}

	else if (bitmap_selector==2)		//ARROW UP setpixel function
	{
		for (int i=0; i<40; i++)
		{
			for (int j=0; j<40; j++)
			{
				int x_pos = j + x;
				int y_pos = i + y;
				UB_VGA_SetPixel(x_pos, y_pos, arrow_up[i][j]);
			}
		}
	}

	else if (bitmap_selector==3)	//ARROW DOWN setpixel function
	{
		for (int i=0; i<40; i++)
		{
			for (int j=0; j<40; j++)
			{
				int x_pos = j + x;
				int y_pos = i + y;
				UB_VGA_SetPixel(x_pos, y_pos, arrow_down[i][j]);
			}
		}
	}

	else if (bitmap_selector==4)		//ARROW RIGHT setpixel function
	{
		for (int i=0; i<40; i++)
		{
			for (int j=0; j<40; j++)
			{
				int x_pos = j + x;
				int y_pos = i + y;
				UB_VGA_SetPixel(x_pos, y_pos, arrow_right[i][j]);
			}
		}
	}

	else if (bitmap_selector==5)		//ARROW LEFT setpixel function
	{
		for (int i=0; i<40; i++)
		{
			for (int j=0; j<40; j++)
			{
				int x_pos = j + x;
				int y_pos = i + y;
				UB_VGA_SetPixel(x_pos, y_pos, arrow_left[i][j]);
			}
		}
	}
*/
}

